version: 2

git:
  # If there are more than one tag in the same commit, pick the newest one
  tag_sort: -version:creatordate
before:
  hooks:
    - go mod download
    - go mod verify
    - make build-browser-api
builds:
  - main: ./cmd/ltagent
    id: "ltagent"
    binary: bin/ltagent
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    env:
      - CGO_ENABLED=0
  - main: ./cmd/ltapi
    id: "ltapi"
    binary: bin/ltapi
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  -
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    formats:
      - tar.gz
    files:
      - LICENSE.txt
      - .nvmrc
      - config/config.sample.json
      - config/browsercontroller.sample.json
      - config/coordinator.sample.json
      - config/simplecontroller.sample.json
      - config/simulcontroller.sample.json
      - browser/dist/**
      - browser/packs/**
      - browser/package.json
      - browser/package-lock.json
      - browser/Makefile
changelog:
  sort: desc
release:
  github:
    owner: mattermost
    name: mattermost-load-test-ng
  prerelease: auto
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
  disable: false
