NumUsersInc = 8
NumUsersDec = 8
RestTimeSec = 2

[ClusterConfig]
MaxActiveUsers = 20000

    [[ClusterConfig.Agents]]
    Id = 'lt0'
    ApiURL = 'http://localhost:4000'

[MonitorConfig]
PrometheusURL = 'http://localhost:9090'
UpdateIntervalMs = 2000

    [[MonitorConfig.Queries]]
    Description = 'Percentage of HTTP 5xx server errors'
    Legend = 'Percent'
    Query = '(sum(rate(mattermost_api_time_count{status_code=~"5.."}[1m]))/sum(rate(mattermost_api_time_count[1m])))*100'
    Threshold = 0.025
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Average client request duration'
    Legend = 'Avg duration (s)'
    Query = 'sum(rate(loadtest_http_request_time_sum[1m]))/sum(rate(loadtest_http_request_time_count[1m]))'
    Threshold = 0.1
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = '99th percentile of client request duration'
    Legend = 'P99 duration (s)'
    Query = 'histogram_quantile(0.99, sum(rate(loadtest_http_request_time_bucket[1m])) by (le))'
    Threshold = 2
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Percentage of HTTP 5xx client errors'
    Legend = 'Percent'
    Query = '(sum(rate(loadtest_http_errors_total{status_code=~"5.."}[1m]))/sum(rate(loadtest_http_request_time_count[1m])))*100'
    Threshold = 0.025
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Percentage of client timeouts'
    Legend = 'Percent'
    Query = '(sum(rate(loadtest_http_timeouts_total[1m]))/sum(rate(loadtest_http_request_time_count[1m]))) * 100'
    Threshold = 0.025
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'CPU utilization - Average of app nodes'
    Legend = 'Percent'
    Query = '100 - 100 * (avg(irate(node_cpu_seconds_total{instance=~"app.*",mode="idle"}[5m])))'
    Threshold = 85
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Memory utilization - Average of app nodes'
    Legend = 'Percent'
    Query = '100 - 100 * avg(node_memory_MemAvailable_bytes{instance=~"app.*"} / node_memory_MemTotal_bytes{instance=~"app.*"})'
    Threshold = 85
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Percentage of TCP retransmissions in the app nodes'
    Legend = 'Percent'
    Query = '(avg(rate(node_netstat_Tcp_RetransSegs{instance=~"app.*"}[1m])) / avg(rate(node_netstat_Tcp_OutSegs{instance=~"app.*"}[1m]))) * 100'
    Threshold = 0.5
    MinIntervalSec = 60
    Alert = true

    [[MonitorConfig.Queries]]
    Description = 'Percentage of TCP retransmissions in the proxy node'
    Legend = 'Percent'
    Query = '(avg(rate(node_netstat_Tcp_RetransSegs{instance=~"proxy:9100"}[1m])) / avg(rate(node_netstat_Tcp_OutSegs{instance=~"proxy:9100"}[1m]))) * 100'
    Threshold = 0.5
    MinIntervalSec = 60
    Alert = true

[LogSettings]
EnableConsole = true
ConsoleLevel = 'INFO'
ConsoleJson = false
EnableFile = true
FileLevel = 'INFO'
FileJson = true
FileLocation = 'ltcoordinator.log'
EnableColor = false
