{
 "title": "Mattermost Load-Test Performance Monitoring",
 "tags": [
  "mattermost",
  "mattermost-perf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Posts per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_post_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(mattermost_post_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_http_requests_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(rate(mattermost_http_requests_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connected Devices (WebSocket Connections)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_http_websockets_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_http_websockets_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connections to Master Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_master_connections_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_db_master_connections_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "API Request Time (Server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_api_time_sum[1m])) by (instance) / sum(rate(mattermost_api_time_count[1m])) by (instance)",
     "legendFormat": "avg-{{ instance }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_api_time_bucket[1m])) by (instance,le))",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Store Call Time (Server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_db_store_time_sum[1m])) by (instance) / sum(rate(mattermost_db_store_time_count[1m])) by (instance)",
     "legendFormat": "avg-{{ instance }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_db_store_time_bucket[1m])) by (instance,le))",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "API Request Time (Client)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loadtest_http_request_time_sum[1m])) by (instance) / sum(rate(loadtest_http_request_time_count[1m])) by (instance)",
     "legendFormat": "avg-{{ instance }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loadtest_http_request_time_bucket[1m])) by (instance,le))",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Rate (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Utilization Rate (%)" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_process_cpu_seconds_total{instance=~\"$server\"}[1m])* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$server\"}",
     "legendFormat": "Alloc-{{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$server\"}",
     "legendFormat": "StackAlloc-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$server\"}",
     "legendFormat": "HeapAlloc-{{instance}}"
    }
   ]
  },
  {
   "title": "Client Timeouts per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loadtest_http_timeouts_total{instance=~\"$server\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(increase(loadtest_http_timeouts_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Load (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{instance=~\"$server\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "User {{instance}}"
    },
    {
     "expr": "sum(rate(node_cpu{instance=~\"$server\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "System {{instance}}"
    },
    {
     "expr": "sum(rate(node_cpu{instance=~\"$server\",mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "Idle {{instance}}"
    },
    {
     "expr": "sum(rate(node_cpu{instance=~\"$server\",mode=~\"irq|softirq|iowait\"}[1m])) by (instance)",
     "legendFormat": "Other {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Errors per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loadtest_http_errors_total{instance=~\"$server\"}[1m])) by (status_code)",
     "legendFormat": "agent - {{ status_code }} "
    },
    {
     "expr": "sum(increase(mattermost_api_time_count{instance=~\"$server\",status_code=~\"4..|5..\"}[1m])) by (status_code)",
     "legendFormat": "app - {{ status_code }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_bytes{instance=~\"$server\"}[1m])) by (instance))*8",
     "legendFormat": "TX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$server\"}[1m])) by (instance))*8",
     "legendFormat": "RX Rate {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"} - node_memory_Buffers{instance=~\"$server\"} - node_memory_Cached{instance=~\"$server\"})",
     "legendFormat": "Used {{ instance }}"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "Total {{ instance }}"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$server\"}",
     "legendFormat": "Established {{ instance }}"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$server\"}[1m])",
     "legendFormat": "Timeouts {{ instance }}"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$server\"})",
     "legendFormat": "Total Established"
    },
    {
     "expr": "sum(irate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total Timeouts"
    }
   ]
  }
 ]
}