{
 "title": "Elasticsearch monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Query rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Queries/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total[1m])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Documents indexing/deletion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Ops/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total[1m])",
     "legendFormat": "indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total[1m])",
     "legendFormat": "deletions"
    }
   ]
  },
  {
   "title": "Documents indexed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elasticsearch_indices_docs", "legendFormat": "docs" },
    {
     "expr": "elasticsearch_indices_docs_deleted    ",
     "legendFormat": "docs deleted"
    }
   ]
  },
  {
   "title": "Stored index size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  { "title": "Cloudwatch metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Notes on Cloudwatch metrics",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "The metrics in this section come from [AWS Cloudwatch](https://aws.amazon.com/cloudwatch/) through the [YACE exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter). Note that all metrics have a resolution and a delay of 5 minutes. That is:\n- There is only one data point every five minutes\n- The last data point is at least 5 minutes old\n\nAll resources in AWS are tagged with:\n- `ClusterName`: the name of the load-test cluster\n- `Name`: the name of the specific resource\n\nYou can filter by such tags using `tag_ClusterName` and `tag_Name`, as in:\n```\nsum(aws_rds_cpuutilization_average) by (tag_Name)\n```"
   }
  },
  {
   "title": "Cluster status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_maximum + aws_es_cluster_status_yellow_maximum * 100 + aws_es_cluster_status_red_maximum * 1000",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(aws_es_cpuutilization_average{dimension_NodeId=~\".+\"}) by (dimension_NodeId)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(aws_es_free_storage_space_sum{dimension_NodeId=~\".+\"} / 1024) by (dimension_NodeId)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}