{
 "title": "MS Teams (By Instance)",
 "description": "A dashboard for use with the Mattermost MSTeams Connect plugin.",
 "tags": [
  "mattermost",
  "msteams"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "top_plugin_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_count[${__range_s}s])) by (api_name)))"
    }
   },
   {
    "name": "top_plugin_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_sum[${__range_s}s])) by (api_name) / sum(increase(mattermost_plugin_api_time_count[${__range_s}s])) by (api_name)))"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_sum[${__range_s}s])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count[${__range_s}s])) by (method)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "MS Teams Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "The total number of Mattermost users connected to MS Teams users.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_connected_users)",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Whitelist Limit",
   "type": "stat",
   "description": "The maximum number of Mattermost users allowed to connect to MS Teams.",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_whitelist_limit)",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Linked Channels",
   "type": "stat",
   "description": "The total number of linked channels to MS Teams.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_linked_channels)",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "MS Teams Users",
   "type": "stat",
   "description": "The total number of MS Teams users detected upstream during the sync job.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_upstream_users)",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "Synthetic Users",
   "type": "stat",
   "description": "The total number of synthetic users.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_synthetic_users)",
     "legendFormat": "Synthetic Users"
    }
   ]
  },
  {
   "title": "Plugin Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(msteams_connect_system_plugin_info{job=\"msteams\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Client Secret Expiry",
   "type": "stat",
   "description": "When the application client secret expires.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(msteams_connect_msgraph_client_secret_end_date_timestamp_seconds{job=\"msteams\"}  * 1000)",
     "legendFormat": "Expiry Timestamp"
    }
   ]
  },
  {
   "title": "Client Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Calls (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m] offset 7d)) ",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_count[5m])) by (instance)",
     "legendFormat": "{{instance [Legacy]}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_count[5m]))",
     "legendFormat": "Total [Legacy]"
    }
   ]
  },
  {
   "title": "HTTP Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_http_requests_total[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "rate(msteams_connect_http_requests_total[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}}) [Legacy]"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}}) [Legacy]"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}}) [Legacy]"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}}) [Legacy]"
    }
   ]
  },
  {
   "title": "DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_count[5m])) by (method)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(increase(msteams_connect_db_store_time_count[5m])) by (method)",
     "legendFormat": "{{method}} [Legacy]"
    }
   ]
  },
  {
   "title": "API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_count[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "sum(increase(msteams_connect_api_time_count[5m])) by (handler)",
     "legendFormat": "{{handler}} [Legacy]"
    }
   ]
  },
  {
   "title": "DB calls by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_sum[5m])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count[5m])) by (method)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(increase(msteams_connect_db_store_time_sum[5m])) by (method) / sum(increase(msteams_connect_db_store_time_count[5m])) by (method)",
     "legendFormat": "{{method}} [Legacy]"
    }
   ]
  },
  {
   "title": "API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum[5m])) by (handler) / sum(increase(msteams_connect_api_time_seconds_count[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "sum(increase(msteams_connect_api_time_sum[5m])) by (handler) / sum(increase(msteams_connect_api_time_count[5m])) by (handler)",
     "legendFormat": "{{handler}} [Legacy]"
    }
   ]
  },
  {
   "title": "Goroutine Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_system_plugin_goroutine_failures_total[5m])) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(msteams_connect_http_errors_total[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  { "title": "MS Graph API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "MS Graph Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) by (instance)",
     "legendFormat": "Requests ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count[5m])) by (instance)",
     "legendFormat": "Requests ({{instance}}) [Legacy]"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count[5m]))",
     "legendFormat": "Total [Legacy]"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}}) [Legacy]"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{success!=\"true\"}[5m]))",
     "legendFormat": "Total [Legacy]"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{method=~\"$top_msgraph_client_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count[5m])) by (method)",
     "legendFormat": "{{method}} [Legacy]"
    }
   ]
  },
  {
   "title": "MS Graph Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}}) [Legacy]"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_bucket[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}}) [Legacy]"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_sum{method=~\"$top_msgraph_client_latency\"}[5m])) by (method) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{method=~\"$top_msgraph_client_latency\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Error Rate",
   "type": "timeseries",
   "description": "Percentage of client requests failing.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MS Graph client Requests by Count (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success=\"false\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalidated oAuth Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_oauth_token_invalidated_total[5m]))",
     "legendFormat": "Invalidated Tokens"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Change Event Queue",
   "type": "timeseries",
   "description": "The number of events currently in the change event queue and awaiting processing by an available goroutine, as well as the number of events rejected because the queue was full.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_app_change_event_queue_length[5m])) by (instance)",
     "legendFormat": "Length {{instance}}"
    },
    {
     "expr": "sum(increase(msteams_connect_events_change_event_queue_rejected_total[5m])) by (instance)",
     "legendFormat": "Rejected {{instance}}"
    }
   ]
  },
  {
   "title": "Processed Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(msteams_connect_events_processed_change_event_total{discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "{{change_type}} [Legacy]"
    }
   ]
  },
  {
   "title": "Discarded Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 99 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(msteams_connect_events_processed_change_event_total{discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "{{discarded_reason}} [Legacy]"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_change_events_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total[5m])) by (event_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_event_total[5m])) by (event_type)",
     "legendFormat": "{{event_type}} [Legacy]"
    }
   ]
  },
  {
   "title": "Discarded Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_lifecycle_events_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_total[5m])) by (action)",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_count[5m])) by (action)",
     "legendFormat": "{{action}} [Legacy]"
    }
   ]
  },
  {
   "title": "Messages (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  {
   "title": "Messages (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  {
   "title": "Reactions (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  {
   "title": "Reactions (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  {
   "title": "Files (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  {
   "title": "Files (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}}) [Legacy]"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}}) [Legacy]"
    }
   ]
  },
  { "title": "Plugin API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Top 10 Plugin API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_count\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 Plugin API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_sum{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"msteams\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{job=\"msteams\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "go_goroutines{endpoint=\"msteamsmetrics\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{endpoint=\"msteamsmetrics\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"msteams\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{endpoint=\"msteamsmetrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "targets": [
    {
     "expr": "sum(msteams_connect_app_active_workers_total) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Workers Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_app_workers_time_seconds_bucket[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_app_workers_time_seconds_bucket[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p50"
    }
   ]
  },
  {
   "title": "DB Connections (Whole Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total)",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total)",
     "legendFormat": "replica"
    }
   ]
  }
 ]
}