# Server-side tuning (Mattermost app nodes + nginx proxy), lifted from
# deployment/terraform/strings.go:serverSysctlConfig.

net.ipv4.ip_local_port_range = 1025 65000
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1

net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 8192

vm.min_free_kbytes = 167772

net.ipv4.tcp_slow_start_after_idle = 0

net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq
net.ipv4.tcp_notsent_lowat = 16384

net.ipv4.tcp_rmem = 4096 156250 2500000
net.ipv4.tcp_wmem = 4096 156250 2500000
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
