name: ci
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.18.4"
          cache: true

      - name: ci/pre-init
        run: |
          make assets
          echo "Checking if 'make assets' was ran after adding files..."
          git diff --exit-code

      - name: ci/verify
        run: make verify-gomod

      - name: ci/check-style
        run: make check-style

      - name: ci/test
        run: make test
